CREATE TABLE View_IIs(
	IIID int NOT NULL,
	IICount int NOT NULL,
	ActiveIICount int NULL,
	IICode varchar(15) NULL,
	ApplicationDate timestamp  NULL,
	ApplicationStatusID int NULL,
	PersonID int NOT NULL,
	ElectoralID varchar(100) NULL,
	NationalIDCard varchar(100) NULL,
	NameCode varchar(15) NULL,
	IIName_ENG varchar(300) NULL,
	IIName_NAT varchar(300) NULL,
	IIName_POR varchar(300) NULL,
	SocialAnimatorID int NULL,
	PaymentStatusID int NULL,
	BeneficiaryTypeID int NOT NULL,
	DisabilityTypeID int NOT NULL,
	DisabilityLevelID int NOT NULL,
	SocialAnimator_ENG varchar(150) NULL,
	SocialAnimator_NAT varchar(150) NULL,
	SocialAnimator_POR varchar(150) NULL,
	DateUpdated timestamp  NULL,
	DateCreated timestamp  NULL,
	UpdatedUser varchar(101) NULL,
	CreatedUser varchar(101) NULL,
	Statusname_ENG varchar(150) NULL,
	Statusname_NAT varchar(150) NULL,
	Statusname_POR varchar(150) NOT NULL,
	Beneficiaryname_ENG varchar(150) NULL,
	Beneficiaryname_NAT varchar(150) NULL,
	Beneficiaryname_POR varchar(150) NULL,
	GenderName_ENG varchar(150) NULL,
	GenderName_NAT varchar(150) NULL,
	GenderName_POR varchar(150) NULL,
	BenefitingProgram_ENG varchar(4000) NULL,
	BenefitingProgram_NAT varchar(4000) NULL,
	BenefitingProgram_POR varchar(4000) NULL,
	NationalityName_ENG varchar(150) NULL,
	NationalityName_NAT varchar(150) NULL,
	NationalityName_POR varchar(150) NULL,
	MaritalStatusName_ENG varchar(150) NULL,
	MaritalStatusName_NAT varchar(150) NULL,
	MaritalStatusName_POR varchar(150) NULL,
	Religion_ENG varchar(150) NULL,
	Religion_NAT varchar(150) NULL,
	Religion_POR varchar(150) NULL,
	MonthlyAmount_USD decimal(30, 2) NULL,
	Phone varchar(150) NULL,
	DateVerified timestamp  NULL,
	OwnerID int NULL,
	ReligionID int NULL,
	StateProgramID int NULL,
	PRIMARY KEY(IIID)
)