CREATE TABLE View_IIs(
	IIID int NOT NULL,
	IICount int NOT NULL,
	ActiveIICount int NULL,
	IICode nvarchar(15) NULL,
	ApplicationDate datetime NULL,
	ApplicationStatusID int NULL,
	PersonID int NOT NULL,
	ElectoralID nvarchar(100) NULL,
	NationalIDCard nvarchar(100) NULL,
	NameCode nvarchar(15) NULL,
	IIName_ENG nvarchar(300) NULL,
	IIName_NAT nvarchar(300) NULL,
	IIName_POR nvarchar(300) NULL,
	SocialAnimatorID int NULL,
	PaymentStatusID int NULL,
	BeneficiaryTypeID int NOT NULL,
	DisabilityTypeID int NOT NULL,
	DisabilityLevelID int NOT NULL,
	SocialAnimator_ENG nvarchar(150) NULL,
	SocialAnimator_NAT nvarchar(150) NULL,
	SocialAnimator_POR nvarchar(150) NULL,
	DateUpdated datetime NULL,
	DateCreated datetime NULL,
	UpdatedUser nvarchar(101) NULL,
	CreatedUser nvarchar(101) NULL,
	Statusname_ENG nvarchar(150) NULL,
	Statusname_NAT nvarchar(150) NULL,
	Statusname_POR nvarchar(150) NOT NULL,
	Beneficiaryname_ENG nvarchar(150) NULL,
	Beneficiaryname_NAT nvarchar(150) NULL,
	Beneficiaryname_POR nvarchar(150) NULL,
	GenderName_ENG nvarchar(150) NULL,
	GenderName_NAT nvarchar(150) NULL,
	GenderName_POR nvarchar(150) NULL,
	BenefitingProgram_ENG nvarchar(4000) NULL,
	BenefitingProgram_NAT nvarchar(4000) NULL,
	BenefitingProgram_POR nvarchar(4000) NULL,
	NationalityName_ENG nvarchar(150) NULL,
	NationalityName_NAT nvarchar(150) NULL,
	NationalityName_POR nvarchar(150) NULL,
	MaritalStatusName_ENG nvarchar(150) NULL,
	MaritalStatusName_NAT nvarchar(150) NULL,
	MaritalStatusName_POR nvarchar(150) NULL,
	Religion_ENG nvarchar(150) NULL,
	Religion_NAT nvarchar(150) NULL,
	Religion_POR nvarchar(150) NULL,
	MonthlyAmount_USD decimal(30, 2) NULL,
	Phone varchar(150) NULL,
	DateVerified datetime NULL,
	OwnerID int NULL,
	ReligionID int NULL,
	StateProgramID int NULL,
	PRIMARY KEY(IIID)
)